INSERT INTO ADRESS(street, CEP, number, city, status_adress) VALUES('albuquerque', '25976-810','2547','Teresopolis','main_adress')
INSERT INTO ADRESS(street, CEP, number, city, status_adress) VALUES('isaias vidal', '25976-810','2547','Teresopolis','noMain_adress')
INSERT INTO ADRESS(street, CEP, number, city, status_adress) VALUES('norte', '25976-810','2547','Teresopolis','noMain_adress')
INSERT INTO ADRESS(street, CEP, number, city, status_adress) VALUES('avenida monte belo', '25976-810','2547','Teresopolis','main_adress')
INSERT INTO ADRESS(street, CEP, number, city, status_adress) VALUES('testes', '25976-810','2547','Teresopolis','noMain_adress')
INSERT INTO ADRESS(street, CEP, number, city, status_adress) VALUES('canoas', '25976-810','2547','Teresopolis','main_adress')
INSERT INTO ADRESS(street, CEP, number, city, status_adress) VALUES('delfim moreira', '25976-810','2547','Teresopolis','main_adress')
INSERT INTO ADRESS(street, CEP, number, city, status_adress) VALUES('albuquerque', '25976-810','2547','Teresopolis','main_adress')
INSERT INTO ADRESS(street, CEP, number, city, status_adress) VALUES('albuquerque', '25976-810','2547','Teresopolis','noMain_adress')
INSERT INTO ADRESS(street, CEP, number, city, status_adress) VALUES('albuquerque', '25976-810','2547','Teresopolis','main_adress')
INSERT INTO ADRESS(street, CEP, number, city, status_adress) VALUES('albuquerque', '25976-810','2547','Teresopolis','noMain_adress')
INSERT INTO ADRESS(street, CEP, number, city, status_adress) VALUES('albuquerque', '25976-810','2547','Teresopolis','noMain_adress')





