INSERT INTO ADRESS(street, CEP, number, city, status_adress) VALUES('albuquerque', '25976-810','2547','Teresopolis','main_adress')
INSERT INTO ADRESS(street, CEP, number, city, status_adress) VALUES('isaias vidal', '25976-810','2547','Teresopolis','noMain_adress')
INSERT INTO ADRESS(street, CEP, number, city, status_adress) VALUES('norte', '25976-810','2547','Teresopolis','noMain_adress')
INSERT INTO ADRESS(street, CEP, number, city, status_adress) VALUES('avenida monte belo', '25976-810','2547','Teresopolis','main_adress')
INSERT INTO ADRESS(street, CEP, number, city, status_adress) VALUES('testes', '25976-810','2547','Teresopolis','noMain_adress')
INSERT INTO ADRESS(street, CEP, number, city, status_adress) VALUES('canoas', '25976-810','2547','Teresopolis','main_adress')
INSERT INTO ADRESS(street, CEP, number, city, status_adress) VALUES('delfim moreira', '25976-810','2547','Teresopolis','main_adress')
INSERT INTO ADRESS(street, CEP, number, city, status_adress) VALUES('albuquerque', '25976-810','2547','Teresopolis','main_adress')
INSERT INTO ADRESS(street, CEP, number, city, status_adress) VALUES('albuquerque', '25976-810','2547','Teresopolis','noMain_adress')
INSERT INTO ADRESS(street, CEP, number, city, status_adress) VALUES('albuquerque', '25976-810','2547','Teresopolis','main_adress')
INSERT INTO ADRESS(street, CEP, number, city, status_adress) VALUES('albuquerque', '25976-810','2547','Teresopolis','noMain_adress')
INSERT INTO ADRESS(street, CEP, number, city, status_adress) VALUES('albuquerque', '25976-810','2547','Teresopolis','noMain_adress')


INSERT INTO PERSON(birthday, name) VALUES('2016-02-11', 'matheus')
INSERT INTO PERSON(birthday, name) VALUES('2016-02-11', 'charlles')
INSERT INTO PERSON(birthday, name) VALUES('2016-02-11', 'josue')
INSERT INTO PERSON(birthday, name) VALUES('2016-02-11', 'olek')
INSERT INTO PERSON(birthday, name) VALUES('2016-02-11', 'ramos')


INSERT INTO PERSON_LIST_OF_ADRESS(person_id, list_of_adress_id) VALUES('1', '1')
INSERT INTO PERSON_LIST_OF_ADRESS(person_id, list_of_adress_id) VALUES('1', '2')
INSERT INTO PERSON_LIST_OF_ADRESS(person_id, list_of_adress_id) VALUES('1', '3')
INSERT INTO PERSON_LIST_OF_ADRESS(person_id, list_of_adress_id) VALUES('1', '4')
INSERT INTO PERSON_LIST_OF_ADRESS(person_id, list_of_adress_id) VALUES('1', '5')
INSERT INTO PERSON_LIST_OF_ADRESS(person_id, list_of_adress_id) VALUES('1', '7')

INSERT INTO PERSON_LIST_OF_ADRESS(person_id, list_of_adress_id) VALUES('2', '1')
INSERT INTO PERSON_LIST_OF_ADRESS(person_id, list_of_adress_id) VALUES('2', '2')
INSERT INTO PERSON_LIST_OF_ADRESS(person_id, list_of_adress_id) VALUES('2', '3')
INSERT INTO PERSON_LIST_OF_ADRESS(person_id, list_of_adress_id) VALUES('2', '4')
INSERT INTO PERSON_LIST_OF_ADRESS(person_id, list_of_adress_id) VALUES('3', '5')
INSERT INTO PERSON_LIST_OF_ADRESS(person_id, list_of_adress_id) VALUES('3', '7')


